# GLOBAL SITE SETTINGS

# Social Networks
twitter: "https://twitter.com/DannyBeaton"
youtube: "https://www.youtube.com/channel/UCdQiykMwQXT_hLHmlgZ54FQ"
facebook: "https://facebook.com/dannybeatonwriter"
instagram: "http://instagram.com/dannybeaton"
tumblr: "http://dannybeaton.tumblr.com/"

# Order the primary navigation (skip home) : add for dropdown - 'second_level: products'
primary_navigation:
 - {title: Author, icon: fi-pencil, url: "/author/", img_icon: "/img/content/mug-icon@2x.png"}
 - {title: Books, icon: fi-book-bookmark, url: "/books/", img_icon: "/img/content/book-icon@2x.png"}
 - {title: Talks, icon: fi-megaphone, url: "/talks/", img_icon: "/img/content/speaker-icon@2x.png"}
 - {title: Store, icon: fi-shopping-cart, url: "/store/", img_icon: "/img/content/cart-icon@2x.png"}
 - {title: Contact, icon: fi-mail, url: "/contact/", img_icon: "/img/content/envelope-icon@2x.png"}